Migrating back toward minimal differences from the original
Because nmatched ''s **MAY** be the only issue in Bash 3.x for the crazy quoting struct

diff --git a/build b/build
--- a/build
+++ b/build
@@ -10,8 +10,11 @@ if [ -n "${ZSH_VERSION:-}" ]; then
 fi
 
 export LC_ALL=C
-
-usage='
+# DDD make sure ''s are matching, THEN use original \END, not 'END'
+# DDD ...and see that the they are preserved, like the '' arg at line ~298:
+#     command git -C "$workdir"/repo commit --allow-empty --allow-empty-message --no-gpg-sign -m ""
+#     ...also ~94, ~303.
+usage="$(command cat <<'END'
 Usage: build [-m ARCH] [-c CPU] [-d CMD] [-i IMAGE] [-s] [-w]
 
 Options:
@@ -29,10 +32,12 @@ Options:
             succeed; on some operating systems this option is not
             supported; on others it can have partial effect
   -w        automatically download tarballs for dependencies if they
-            don'\''t already exist in ./deps; dependencies are described
+            don not already exist in ./deps; dependencies are described
             in ./build.info
-'
-build='
+END
+)"
+
+build="$(command cat <<'END'
 outdir="$(command pwd)"
 
 if command -v mktemp >/dev/null 2>&1; then
@@ -87,7 +92,7 @@ if [ -n "$gitstatus_install_tools" ]; then
     ;;
     darwin)
       if ! command -v make >/dev/null 2>&1 || ! command -v gcc >/dev/null 2>&1; then
-        >&2 echo "[error] please run '\''xcode-select --install'\'' and retry"
+        >&2 echo "[error] please run 'xcode-select --install' and retry"
         exit 1
       fi
       if ! command -v brew >/dev/null 2>&1; then
@@ -230,7 +235,7 @@ elif command -v sha256sum >/dev/null 2>/dev/null; then
   libgit2_actual_sha256="${libgit2_actual_sha256%% *}"
 elif command -v sha256 >/dev/null 2>/dev/null; then
   libgit2_actual_sha256="$(command sha256 -- "$libgit2_tarball" </dev/null)"
-  # Ignore sha256 output if it'\''s from hashalot. It'\''s incompatible.
+  # Ignore sha256 output if it's from hashalot. It's incompatible.
   if [ ${#libgit2_actual_sha256} -lt 64 ]; then
     libgit2_actual_sha256=
   else
@@ -296,7 +301,7 @@ command git -C "$workdir"/repo commit --allow-empty --allow-empty-message --no-g
 resp="$(printf "hello\037$workdir/repo\036" | "$app".tmp)"
 [ -n "$resp" -a -z "${resp##hello*1*$workdir/repo*master*}" ]
 
-resp="$(printf '\''hello\037\036'\'' | "$app".tmp)"
+resp="$(printf 'hello\037\036' | "$app".tmp)"
 [ -n "$resp" -a -z "${resp##hello*0*}" ]
 
 command mv -f -- "$app".tmp "$app"
@@ -306,8 +311,9 @@ cleanup
 command cat >&2 <<-END
 	-------------------------------------------------
 	SUCCESS: created usrbin/$appname
-	END
-'
+  END
+END
+)"
 
 docker_image=
 docker_cmd=
